# Development Docker Compose Configuration
version: '3.8'

services:
  vedic-astrology-dev:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - REPLIT_DEV_DOMAIN=localhost
      - DATA_DIR=/app/data
    volumes:
      # Hot reload - mount source code
      - ./main.py:/app/main.py
      - ./static:/app/static
      - ./ephe:/app/ephe:ro
      # Persistent data
      - dev_db:/app/data
      - dev_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  dev_db:
  dev_logs: